### ISSUE TITLE
Shark Ticking Entity crashes dedicated server

### ISSUE THREAD

**Issue by karltroid51** [RayTrace082/untamedwilds#26]
Hi! We are using your mod on our dedicated server, and recently there have been crashes because of a shark. Attached is our crash log. Thank you for any help in advance!

[crash-2021-07-02_08.10.07-server.txt](https://github.com/RayTrace082/untamedwilds/files/6753121/crash-2021-07-02_08.10.07-server.txt)

**Comment by RayTrace082** [comment]
Most likely fixed in the latest hotfix, will close issue if no further issues arise

**Comment by DigitalWendigo** [comment]
[crash-2022-10-05_18.17.37-server.txt](https://github.com/RayTrace082/untamedwilds/files/9716947/crash-2022-10-05_18.17.37-server.txt)
Unfortunately this is still present in the last 1.16.5. version of the mod. 
Not entirely sure if it's the exact same thing, but it mentions a ticking entity, which is apparently also a shark.
